import type { DomainTelemetry, ProcessMetricRow } from "./monitoringTypes";

let tickCounter = 0;

export function generateIdleTelemetry(): DomainTelemetry {
  const zeroHistory = Array(12).fill(0);
  const idleProcesses: ProcessMetricRow[] = [
    {
      id: "p-eth0",
      name: "Ethernet Primary (en0)",
      type: "Network Interface",
      bandwidthBytes: 0,
      formattedBandwidth: "0 B/s",
      utilizationPercent: 0,
      cpuPercent: 0,
      memoryMB: 148,
      packetsPerSec: 0,
      rttMs: 0,
      errors: 0,
      color: "var(--np-monitor-primary, #00f2fe)",
      history: Array(10).fill(0),
    },
    {
      id: "p-socket",
      name: "Bound Wave Socket",
      type: "Local Socket",
      bandwidthBytes: 0,
      formattedBandwidth: "0 B/s",
      utilizationPercent: 0,
      cpuPercent: 0,
      memoryMB: 64,
      packetsPerSec: 0,
      rttMs: 0,
      errors: 0,
      color: "var(--np-monitor-accent, #06b6d4)",
      history: Array(10).fill(0),
    },
    {
      id: "p-subnet",
      name: "Ethernet Sec Subnet",
      type: "VLAN Adapter",
      bandwidthBytes: 0,
      formattedBandwidth: "0 B/s",
      utilizationPercent: 0,
      cpuPercent: 0,
      memoryMB: 92,
      packetsPerSec: 0,
      rttMs: 0,
      errors: 0,
      color: "var(--np-monitor-warning, #f59e0b)",
      history: Array(10).fill(0),
    },
    {
      id: "p-otm",
      name: "OTM Wi-Fi Adapter",
      type: "Wireless Interface",
      bandwidthBytes: 0,
      formattedBandwidth: "0 B/s",
      utilizationPercent: 0,
      cpuPercent: 0,
      memoryMB: 38,
      packetsPerSec: 0,
      rttMs: 0,
      errors: 0,
      color: "var(--np-monitor-danger, #ef4444)",
      history: Array(10).fill(0),
    },
    {
      id: "p-ebpf",
      name: "eBPF Collector Engine",
      type: "Kernel Probe",
      bandwidthBytes: 0,
      formattedBandwidth: "0 B/s",
      utilizationPercent: 0,
      cpuPercent: 0,
      memoryMB: 210,
      packetsPerSec: 0,
      rttMs: 0,
      errors: 0,
      color: "var(--np-monitor-primary, #00f2fe)",
      history: Array(10).fill(0),
    },
    {
      id: "p-dns",
      name: "DNS Resolver Socket",
      type: "Socket Listener",
      bandwidthBytes: 0,
      formattedBandwidth: "0 B/s",
      utilizationPercent: 0,
      cpuPercent: 0,
      memoryMB: 28,
      packetsPerSec: 0,
      rttMs: 0,
      errors: 0,
      color: "var(--np-monitor-accent, #06b6d4)",
      history: Array(10).fill(0),
    },
    {
      id: "p-tls",
      name: "TLS Decryption Proxy",
      type: "Crypto Engine",
      bandwidthBytes: 0,
      formattedBandwidth: "0 B/s",
      utilizationPercent: 0,
      cpuPercent: 0,
      memoryMB: 310,
      packetsPerSec: 0,
      rttMs: 0,
      errors: 0,
      color: "var(--np-monitor-warning, #f59e0b)",
      history: Array(10).fill(0),
    },
    {
      id: "p-ring",
      name: "Ring Buffer Allocator",
      type: "Memory Manager",
      bandwidthBytes: 0,
      formattedBandwidth: "0 B/s",
      utilizationPercent: 0,
      cpuPercent: 0,
      memoryMB: 512,
      packetsPerSec: 0,
      rttMs: 0,
      errors: 0,
      color: "var(--np-monitor-success, #10b981)",
      history: Array(10).fill(0),
    },
  ];

  return {
    timestampNanos: Date.now() * 1000000,
    bytesSeen: 0,
    activeFlows: 0,
    activeHosts: 0,
    activeProtocols: 0,
    ingressHistory: zeroHistory,
    egressHistory: zeroHistory,
    gainsHistory: zeroHistory,
    nodes: [
      { id: "enc", label: "Encryption (AES)", sublabel: "0 B/s", status: "healthy", x: 90, y: 50 },
      { id: "orch", label: "Data Orchestration", sublabel: "0 B/s", status: "healthy", x: 410, y: 50 },
      { id: "engine", label: "Telemetry Engine", sublabel: "Bridge Core (Standby)", status: "healthy", x: 250, y: 115 },
      { id: "gateway", label: "Enroute Gateway", sublabel: "0 B/s", status: "healthy", x: 90, y: 180 },
      { id: "event", label: "Event Stream", sublabel: "0 B/s", status: "healthy", x: 410, y: 180 },
    ],
    edges: [
      { source: "enc", target: "engine", bandwidth: "0 B/s", animated: false },
      { source: "orch", target: "engine", bandwidth: "0 B/s", animated: false },
      { source: "gateway", target: "engine", bandwidth: "0 B/s", animated: false },
      { source: "event", target: "engine", bandwidth: "0 B/s", animated: false },
    ],
    processes: idleProcesses,
    bufferPercent: 0,
    bufferFrames: 0,
    bufferCapacity: 1000,
    dropCount: 0,
    networkLossCount: 0,
    diagnoses: [],
  };
}

export function generateSimulationTelemetry(): DomainTelemetry {
  tickCounter++;
  const t = tickCounter;

  // Wave functions for organic-looking chart telemetry
  const baseIngress = 450 + Math.sin(t * 0.3) * 200 + Math.cos(t * 0.7) * 120;
  const baseEgress = 280 + Math.cos(t * 0.4) * 150 + Math.sin(t * 0.8) * 80;
  const baseGains = 120 + Math.sin(t * 0.5) * 140 + (t % 7 === 0 ? 300 : 0);

  const mockProcesses: ProcessMetricRow[] = [
    {
      id: "p-eth0",
      name: "Ethernet Primary (en0)",
      type: "Network Interface",
      bandwidthBytes: 2397000000,
      formattedBandwidth: "2397 MB/s",
      utilizationPercent: 10.3,
      cpuPercent: 12.4,
      memoryMB: 148,
      packetsPerSec: 14200,
      rttMs: 1.2,
      errors: 0,
      color: "var(--np-monitor-primary, #00f2fe)",
      history: [40, 55, 60, 48, 70, 65, 80, 75, 88, 10.3 * 8],
    },
    {
      id: "p-socket",
      name: "Bound Wave Socket",
      type: "Local Socket",
      bandwidthBytes: 53900000,
      formattedBandwidth: "53.9 MB/s",
      utilizationPercent: 5.39,
      cpuPercent: 4.8,
      memoryMB: 64,
      packetsPerSec: 3800,
      rttMs: 0.4,
      errors: 0,
      color: "var(--np-monitor-accent, #06b6d4)",
      history: [30, 42, 38, 50, 45, 52, 48, 60, 55, 5.39 * 8],
    },
    {
      id: "p-subnet",
      name: "Ethernet Sec Subnet",
      type: "VLAN Adapter",
      bandwidthBytes: 68100000,
      formattedBandwidth: "68.1 MB/s",
      utilizationPercent: 6.81,
      cpuPercent: 8.2,
      memoryMB: 92,
      packetsPerSec: 4200,
      rttMs: 2.1,
      errors: 0,
      color: "var(--np-monitor-warning, #f59e0b)",
      history: [20, 35, 40, 32, 48, 42, 50, 58, 62, 6.81 * 8],
    },
    {
      id: "p-otm",
      name: "OTM Wi-Fi Adapter",
      type: "Wireless Interface",
      bandwidthBytes: 3300000,
      formattedBandwidth: "3.3 MB/s",
      utilizationPercent: 3.3,
      cpuPercent: 2.1,
      memoryMB: 38,
      packetsPerSec: 940,
      rttMs: 8.4,
      errors: 0,
      color: "var(--np-monitor-danger, #ef4444)",
      history: [15, 20, 18, 25, 22, 30, 28, 32, 29, 3.3 * 8],
    },
    {
      id: "p-ebpf",
      name: "eBPF Collector Engine",
      type: "Kernel Probe",
      bandwidthBytes: 840000000,
      formattedBandwidth: "840 MB/s",
      utilizationPercent: 8.4,
      cpuPercent: 18.6,
      memoryMB: 210,
      packetsPerSec: 18900,
      rttMs: 0.1,
      errors: 0,
      color: "var(--np-monitor-primary, #00f2fe)",
      history: [50, 62, 68, 75, 80, 85, 90, 82, 84, 88],
    },
    {
      id: "p-dns",
      name: "DNS Resolver Socket",
      type: "Socket Listener",
      bandwidthBytes: 12400000,
      formattedBandwidth: "12.4 MB/s",
      utilizationPercent: 1.24,
      cpuPercent: 1.8,
      memoryMB: 28,
      packetsPerSec: 1400,
      rttMs: 3.2,
      errors: 0,
      color: "var(--np-monitor-accent, #06b6d4)",
      history: [10, 14, 18, 22, 25, 20, 19, 21, 24, 25],
    },
    {
      id: "p-tls",
      name: "TLS Decryption Proxy",
      type: "Crypto Engine",
      bandwidthBytes: 420000000,
      formattedBandwidth: "420 MB/s",
      utilizationPercent: 4.2,
      cpuPercent: 14.2,
      memoryMB: 310,
      packetsPerSec: 9200,
      rttMs: 1.8,
      errors: 0,
      color: "var(--np-monitor-warning, #f59e0b)",
      history: [30, 38, 42, 45, 50, 48, 52, 55, 60, 58],
    },
    {
      id: "p-ring",
      name: "Ring Buffer Allocator",
      type: "Memory Manager",
      bandwidthBytes: 1200000000,
      formattedBandwidth: "1.2 GB/s",
      utilizationPercent: 12.0,
      cpuPercent: 6.4,
      memoryMB: 512,
      packetsPerSec: 24000,
      rttMs: 0.05,
      errors: 0,
      color: "var(--np-monitor-success, #10b981)",
      history: [60, 70, 75, 80, 85, 90, 92, 95, 98, 100],
    },
  ];

  return {
    timestampNanos: Date.now() * 1000000,
    bytesSeen: Math.round(baseIngress + baseEgress) * 1024 * 10,
    activeFlows: 24 + (t % 5),
    activeHosts: 8,
    activeProtocols: 4,
    ingressHistory: [80, 100, 150, 420, 600, 380, 450, 780, 720, 680, 620, Math.round(baseIngress)],
    egressHistory: [40, 50, 80, 210, 300, 190, 220, 390, 360, 340, 310, Math.round(baseEgress)],
    gainsHistory: [120, 140, 250, 150, 220, 180, 270, 160, 120, 110, 120, Math.round(baseGains)],
    nodes: [
      { id: "enc", label: "Encryption (AES)", sublabel: "3.8 MB/s", status: "healthy", x: 90, y: 50 },
      { id: "orch", label: "Data Orchestration", sublabel: "2.8 MB/s", status: "healthy", x: 410, y: 50 },
      { id: "engine", label: "Telemetry Engine", sublabel: "Bridge Core", status: "healthy", x: 250, y: 115 },
      { id: "gateway", label: "Enroute Gateway", sublabel: "5.3 MB/s", status: "healthy", x: 90, y: 180 },
      { id: "event", label: "Event Stream", sublabel: "2.3 MB/s", status: "healthy", x: 410, y: 180 },
    ],
    edges: [
      { source: "enc", target: "engine", bandwidth: "3.8 MB/s", animated: true },
      { source: "orch", target: "engine", bandwidth: "2.8 MB/s", animated: true },
      { source: "gateway", target: "engine", bandwidth: "5.3 MB/s", animated: true },
      { source: "event", target: "engine", bandwidth: "2.3 MB/s", animated: true },
    ],
    processes: mockProcesses,
    bufferPercent: 24 + (t % 15),
    bufferFrames: 240,
    bufferCapacity: 1000,
    dropCount: 0,
    networkLossCount: 0,
    diagnoses: [],
  };
}
