import type { DomainTelemetry } from "./monitoringTypes";

export function generateIdleTelemetry(): DomainTelemetry {
  const zeroHistory = Array(12).fill(0);

  return {
    timestampNanos: Date.now() * 1_000_000,
    bytesSeen: 0,
    activeFlows: 0,
    activeHosts: 0,
    activeProtocols: 0,
    ingressHistory: zeroHistory,
    egressHistory: zeroHistory,
    gainsHistory: zeroHistory,
    nodes: [],
    edges: [],
    processes: [],
    bufferPercent: 0,
    bufferFrames: 0,
    bufferCapacity: 1000,
    dropCount: 0,
    networkLossCount: 0,
    diagnoses: [],
    diagnosticChain: {
      stages: [
        {
          stage: "device",
          status: "unknown",
          measurement_state: "unknown",
          detection_state: "not_detected",
          label: "Device (Local Stack)",
          summary: "Local Engine Standby",
          detail: "No active packet capture stream",
          evidence: [],
          causes: [],
          affected_targets: [],
        },
        {
          stage: "interface",
          status: "unknown",
          measurement_state: "unknown",
          detection_state: "not_detected",
          label: "Network Interface",
          summary: "Interface Standby",
          evidence: [],
          causes: [],
          affected_targets: [],
        },
        {
          stage: "router",
          status: "unknown",
          measurement_state: "unknown",
          detection_state: "not_detected",
          label: "Router / Gateway",
          summary: "Gateway Route Unobserved",
          detail: "No flows observed across gateway in current window",
          evidence: [],
          causes: [],
          affected_targets: [],
        },
        {
          stage: "isp",
          status: "unknown",
          measurement_state: "not_measurable",
          detection_state: "not_detected",
          label: "Internet Service Provider",
          summary: "ISP Upstream Hop Not Sampled",
          detail: "Passive capture does not directly sample upstream ISP infrastructure without active traceroute probe",
          evidence: [],
          causes: [],
          affected_targets: [],
        },
        {
          stage: "dns",
          status: "not_measurable",
          measurement_state: "not_measurable",
          detection_state: "not_detected",
          label: "DNS Resolver",
          summary: "No DNS Queries in Window",
          detail: "No DNS queries observed in current capture window",
          evidence: [],
          causes: [],
          affected_targets: [],
        },
        {
          stage: "cdn",
          status: "not_measurable",
          measurement_state: "not_measurable",
          detection_state: "not_detected",
          label: "CDN / Edge Distribution",
          summary: "No Edge Endpoints in Window",
          detail: "No CDN or edge distribution nodes identified in current active flows",
          evidence: [],
          causes: [],
          affected_targets: [],
        },
        {
          stage: "destination",
          status: "unknown",
          measurement_state: "unknown",
          detection_state: "not_detected",
          label: "Destination Server",
          summary: "No Remote Traffic Observed",
          detail: "Capture standby — start traffic to observe destination health",
          evidence: [],
          causes: [],
          affected_targets: [],
        },
      ],
    },
  };
}
